// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// Permission is an object representing the database table.
type Permission struct {
	ID     uuid.UUID `db:"id,pk" `
	Object string    `db:"object" `
	Action string    `db:"action" `
}

// PermissionSlice is an alias for a slice of pointers to Permission.
// This should almost always be used instead of []*Permission.
type PermissionSlice []*Permission

// Permissions contains methods to work with the permissions table
var Permissions = psql.NewTablex[*Permission, PermissionSlice, *PermissionSetter]("", "permissions", buildPermissionColumns("permissions"))

// PermissionsQuery is a query on the permissions table
type PermissionsQuery = *psql.ViewQuery[*Permission, PermissionSlice]

func buildPermissionColumns(alias string) permissionColumns {
	return permissionColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "object", "action",
		).WithParent("permissions"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		Object:     psql.Quote(alias, "object"),
		Action:     psql.Quote(alias, "action"),
	}
}

type permissionColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	Object     psql.Expression
	Action     psql.Expression
}

func (c permissionColumns) Alias() string {
	return c.tableAlias
}

func (permissionColumns) AliasedAs(alias string) permissionColumns {
	return buildPermissionColumns(alias)
}

// PermissionSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type PermissionSetter struct {
	ID     omit.Val[uuid.UUID] `db:"id,pk" `
	Object omit.Val[string]    `db:"object" `
	Action omit.Val[string]    `db:"action" `
}

func (s PermissionSetter) SetColumns() []string {
	vals := make([]string, 0, 3)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Object.IsValue() {
		vals = append(vals, "object")
	}
	if s.Action.IsValue() {
		vals = append(vals, "action")
	}
	return vals
}

func (s PermissionSetter) Overwrite(t *Permission) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Object.IsValue() {
		t.Object = s.Object.MustGet()
	}
	if s.Action.IsValue() {
		t.Action = s.Action.MustGet()
	}
}

func (s *PermissionSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Permissions.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 3)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Object.IsValue() {
			vals[1] = psql.Arg(s.Object.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Action.IsValue() {
			vals[2] = psql.Arg(s.Action.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s PermissionSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s PermissionSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 3)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Object.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "object")...),
			psql.Arg(s.Object),
		}})
	}

	if s.Action.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "action")...),
			psql.Arg(s.Action),
		}})
	}

	return exprs
}

// FindPermission retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindPermission(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Permission, error) {
	if len(cols) == 0 {
		return Permissions.Query(
			sm.Where(Permissions.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Permissions.Query(
		sm.Where(Permissions.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Permissions.Columns.Only(cols...)),
	).One(ctx, exec)
}

// PermissionExists checks the presence of a single record by primary key
func PermissionExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Permissions.Query(
		sm.Where(Permissions.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Permission is retrieved from the database
func (o *Permission) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Permissions.AfterSelectHooks.RunHooks(ctx, exec, PermissionSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Permissions.AfterInsertHooks.RunHooks(ctx, exec, PermissionSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Permissions.AfterUpdateHooks.RunHooks(ctx, exec, PermissionSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Permissions.AfterDeleteHooks.RunHooks(ctx, exec, PermissionSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Permission
func (o *Permission) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Permission) pkEQ() dialect.Expression {
	return psql.Quote("permissions", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Permission
func (o *Permission) Update(ctx context.Context, exec bob.Executor, s *PermissionSetter) error {
	v, err := Permissions.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single Permission record with an executor
func (o *Permission) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Permissions.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Permission using the executor
func (o *Permission) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Permissions.Query(
		sm.Where(Permissions.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after PermissionSlice is retrieved from the database
func (o PermissionSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Permissions.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Permissions.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Permissions.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Permissions.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o PermissionSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("permissions", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o PermissionSlice) copyMatchingRows(from ...*Permission) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o PermissionSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Permissions.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Permission:
				o.copyMatchingRows(retrieved)
			case []*Permission:
				o.copyMatchingRows(retrieved...)
			case PermissionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Permission or a slice of Permission
				// then run the AfterUpdateHooks on the slice
				_, err = Permissions.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o PermissionSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Permissions.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Permission:
				o.copyMatchingRows(retrieved)
			case []*Permission:
				o.copyMatchingRows(retrieved...)
			case PermissionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Permission or a slice of Permission
				// then run the AfterDeleteHooks on the slice
				_, err = Permissions.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o PermissionSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals PermissionSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Permissions.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o PermissionSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Permissions.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o PermissionSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Permissions.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type permissionWhere[Q psql.Filterable] struct {
	ID     psql.WhereMod[Q, uuid.UUID]
	Object psql.WhereMod[Q, string]
	Action psql.WhereMod[Q, string]
}

func (permissionWhere[Q]) AliasedAs(alias string) permissionWhere[Q] {
	return buildPermissionWhere[Q](buildPermissionColumns(alias))
}

func buildPermissionWhere[Q psql.Filterable](cols permissionColumns) permissionWhere[Q] {
	return permissionWhere[Q]{
		ID:     psql.Where[Q, uuid.UUID](cols.ID),
		Object: psql.Where[Q, string](cols.Object),
		Action: psql.Where[Q, string](cols.Action),
	}
}
