// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// Role is an object representing the database table.
type Role struct {
	ID          uuid.UUID        `db:"id,pk" `
	Name        string           `db:"name" `
	Description null.Val[string] `db:"description" `
	IsSystem    null.Val[bool]   `db:"is_system" `
	CreatedAt   time.Time        `db:"created_at" `
	UpdatedAt   time.Time        `db:"updated_at" `
}

// RoleSlice is an alias for a slice of pointers to Role.
// This should almost always be used instead of []*Role.
type RoleSlice []*Role

// Roles contains methods to work with the roles table
var Roles = psql.NewTablex[*Role, RoleSlice, *RoleSetter]("", "roles", buildRoleColumns("roles"))

// RolesQuery is a query on the roles table
type RolesQuery = *psql.ViewQuery[*Role, RoleSlice]

func buildRoleColumns(alias string) roleColumns {
	return roleColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name", "description", "is_system", "created_at", "updated_at",
		).WithParent("roles"),
		tableAlias:  alias,
		ID:          psql.Quote(alias, "id"),
		Name:        psql.Quote(alias, "name"),
		Description: psql.Quote(alias, "description"),
		IsSystem:    psql.Quote(alias, "is_system"),
		CreatedAt:   psql.Quote(alias, "created_at"),
		UpdatedAt:   psql.Quote(alias, "updated_at"),
	}
}

type roleColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          psql.Expression
	Name        psql.Expression
	Description psql.Expression
	IsSystem    psql.Expression
	CreatedAt   psql.Expression
	UpdatedAt   psql.Expression
}

func (c roleColumns) Alias() string {
	return c.tableAlias
}

func (roleColumns) AliasedAs(alias string) roleColumns {
	return buildRoleColumns(alias)
}

// RoleSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type RoleSetter struct {
	ID          omit.Val[uuid.UUID]  `db:"id,pk" `
	Name        omit.Val[string]     `db:"name" `
	Description omitnull.Val[string] `db:"description" `
	IsSystem    omitnull.Val[bool]   `db:"is_system" `
	CreatedAt   omit.Val[time.Time]  `db:"created_at" `
	UpdatedAt   omit.Val[time.Time]  `db:"updated_at" `
}

func (s RoleSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if !s.Description.IsUnset() {
		vals = append(vals, "description")
	}
	if !s.IsSystem.IsUnset() {
		vals = append(vals, "is_system")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s RoleSetter) Overwrite(t *Role) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if !s.Description.IsUnset() {
		t.Description = s.Description.MustGetNull()
	}
	if !s.IsSystem.IsUnset() {
		t.IsSystem = s.IsSystem.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *RoleSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Roles.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 6)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[1] = psql.Arg(s.Name.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if !s.Description.IsUnset() {
			vals[2] = psql.Arg(s.Description.MustGetNull())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.IsSystem.IsUnset() {
			vals[3] = psql.Arg(s.IsSystem.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[4] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[5] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s RoleSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s RoleSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if !s.Description.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "description")...),
			psql.Arg(s.Description),
		}})
	}

	if !s.IsSystem.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_system")...),
			psql.Arg(s.IsSystem),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindRole retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindRole(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Role, error) {
	if len(cols) == 0 {
		return Roles.Query(
			sm.Where(Roles.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Roles.Query(
		sm.Where(Roles.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Roles.Columns.Only(cols...)),
	).One(ctx, exec)
}

// RoleExists checks the presence of a single record by primary key
func RoleExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Roles.Query(
		sm.Where(Roles.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Role is retrieved from the database
func (o *Role) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Roles.AfterSelectHooks.RunHooks(ctx, exec, RoleSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Roles.AfterInsertHooks.RunHooks(ctx, exec, RoleSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Roles.AfterUpdateHooks.RunHooks(ctx, exec, RoleSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Roles.AfterDeleteHooks.RunHooks(ctx, exec, RoleSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Role
func (o *Role) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Role) pkEQ() dialect.Expression {
	return psql.Quote("roles", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Role
func (o *Role) Update(ctx context.Context, exec bob.Executor, s *RoleSetter) error {
	v, err := Roles.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single Role record with an executor
func (o *Role) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Roles.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Role using the executor
func (o *Role) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Roles.Query(
		sm.Where(Roles.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after RoleSlice is retrieved from the database
func (o RoleSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Roles.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Roles.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Roles.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Roles.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o RoleSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("roles", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o RoleSlice) copyMatchingRows(from ...*Role) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o RoleSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Roles.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Role:
				o.copyMatchingRows(retrieved)
			case []*Role:
				o.copyMatchingRows(retrieved...)
			case RoleSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Role or a slice of Role
				// then run the AfterUpdateHooks on the slice
				_, err = Roles.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o RoleSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Roles.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Role:
				o.copyMatchingRows(retrieved)
			case []*Role:
				o.copyMatchingRows(retrieved...)
			case RoleSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Role or a slice of Role
				// then run the AfterDeleteHooks on the slice
				_, err = Roles.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o RoleSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals RoleSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Roles.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o RoleSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Roles.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o RoleSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Roles.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type roleWhere[Q psql.Filterable] struct {
	ID          psql.WhereMod[Q, uuid.UUID]
	Name        psql.WhereMod[Q, string]
	Description psql.WhereNullMod[Q, string]
	IsSystem    psql.WhereNullMod[Q, bool]
	CreatedAt   psql.WhereMod[Q, time.Time]
	UpdatedAt   psql.WhereMod[Q, time.Time]
}

func (roleWhere[Q]) AliasedAs(alias string) roleWhere[Q] {
	return buildRoleWhere[Q](buildRoleColumns(alias))
}

func buildRoleWhere[Q psql.Filterable](cols roleColumns) roleWhere[Q] {
	return roleWhere[Q]{
		ID:          psql.Where[Q, uuid.UUID](cols.ID),
		Name:        psql.Where[Q, string](cols.Name),
		Description: psql.WhereNull[Q, string](cols.Description),
		IsSystem:    psql.WhereNull[Q, bool](cols.IsSystem),
		CreatedAt:   psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:   psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}
