// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Session is an object representing the database table.
type Session struct {
	ID           uuid.UUID              `db:"id,pk" `
	UserID       uuid.UUID              `db:"user_id" `
	RefreshJti   uuid.UUID              `db:"refresh_jti" `
	TokenVersion int32                  `db:"token_version" `
	DeviceName   null.Val[string]       `db:"device_name" `
	UserAgent    null.Val[string]       `db:"user_agent" `
	IPAddress    null.Val[pgtypes.Inet] `db:"ip_address" `
	CreatedAt    time.Time              `db:"created_at" `
	ExpiresAt    time.Time              `db:"expires_at" `
	RevokedAt    null.Val[time.Time]    `db:"revoked_at" `

	R sessionR `db:"-" `
}

// SessionSlice is an alias for a slice of pointers to Session.
// This should almost always be used instead of []*Session.
type SessionSlice []*Session

// Sessions contains methods to work with the sessions table
var Sessions = psql.NewTablex[*Session, SessionSlice, *SessionSetter]("", "sessions", buildSessionColumns("sessions"))

// SessionsQuery is a query on the sessions table
type SessionsQuery = *psql.ViewQuery[*Session, SessionSlice]

// sessionR is where relationships are stored.
type sessionR struct {
	User *User // sessions.sessions_user_id_fkey
}

func buildSessionColumns(alias string) sessionColumns {
	return sessionColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "refresh_jti", "token_version", "device_name", "user_agent", "ip_address", "created_at", "expires_at", "revoked_at",
		).WithParent("sessions"),
		tableAlias:   alias,
		ID:           psql.Quote(alias, "id"),
		UserID:       psql.Quote(alias, "user_id"),
		RefreshJti:   psql.Quote(alias, "refresh_jti"),
		TokenVersion: psql.Quote(alias, "token_version"),
		DeviceName:   psql.Quote(alias, "device_name"),
		UserAgent:    psql.Quote(alias, "user_agent"),
		IPAddress:    psql.Quote(alias, "ip_address"),
		CreatedAt:    psql.Quote(alias, "created_at"),
		ExpiresAt:    psql.Quote(alias, "expires_at"),
		RevokedAt:    psql.Quote(alias, "revoked_at"),
	}
}

type sessionColumns struct {
	expr.ColumnsExpr
	tableAlias   string
	ID           psql.Expression
	UserID       psql.Expression
	RefreshJti   psql.Expression
	TokenVersion psql.Expression
	DeviceName   psql.Expression
	UserAgent    psql.Expression
	IPAddress    psql.Expression
	CreatedAt    psql.Expression
	ExpiresAt    psql.Expression
	RevokedAt    psql.Expression
}

func (c sessionColumns) Alias() string {
	return c.tableAlias
}

func (sessionColumns) AliasedAs(alias string) sessionColumns {
	return buildSessionColumns(alias)
}

// SessionSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type SessionSetter struct {
	ID           omit.Val[uuid.UUID]        `db:"id,pk" `
	UserID       omit.Val[uuid.UUID]        `db:"user_id" `
	RefreshJti   omit.Val[uuid.UUID]        `db:"refresh_jti" `
	TokenVersion omit.Val[int32]            `db:"token_version" `
	DeviceName   omitnull.Val[string]       `db:"device_name" `
	UserAgent    omitnull.Val[string]       `db:"user_agent" `
	IPAddress    omitnull.Val[pgtypes.Inet] `db:"ip_address" `
	CreatedAt    omit.Val[time.Time]        `db:"created_at" `
	ExpiresAt    omit.Val[time.Time]        `db:"expires_at" `
	RevokedAt    omitnull.Val[time.Time]    `db:"revoked_at" `
}

func (s SessionSetter) SetColumns() []string {
	vals := make([]string, 0, 10)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.RefreshJti.IsValue() {
		vals = append(vals, "refresh_jti")
	}
	if s.TokenVersion.IsValue() {
		vals = append(vals, "token_version")
	}
	if !s.DeviceName.IsUnset() {
		vals = append(vals, "device_name")
	}
	if !s.UserAgent.IsUnset() {
		vals = append(vals, "user_agent")
	}
	if !s.IPAddress.IsUnset() {
		vals = append(vals, "ip_address")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.ExpiresAt.IsValue() {
		vals = append(vals, "expires_at")
	}
	if !s.RevokedAt.IsUnset() {
		vals = append(vals, "revoked_at")
	}
	return vals
}

func (s SessionSetter) Overwrite(t *Session) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.RefreshJti.IsValue() {
		t.RefreshJti = s.RefreshJti.MustGet()
	}
	if s.TokenVersion.IsValue() {
		t.TokenVersion = s.TokenVersion.MustGet()
	}
	if !s.DeviceName.IsUnset() {
		t.DeviceName = s.DeviceName.MustGetNull()
	}
	if !s.UserAgent.IsUnset() {
		t.UserAgent = s.UserAgent.MustGetNull()
	}
	if !s.IPAddress.IsUnset() {
		t.IPAddress = s.IPAddress.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.ExpiresAt.IsValue() {
		t.ExpiresAt = s.ExpiresAt.MustGet()
	}
	if !s.RevokedAt.IsUnset() {
		t.RevokedAt = s.RevokedAt.MustGetNull()
	}
}

func (s *SessionSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Sessions.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 10)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.RefreshJti.IsValue() {
			vals[2] = psql.Arg(s.RefreshJti.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.TokenVersion.IsValue() {
			vals[3] = psql.Arg(s.TokenVersion.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.DeviceName.IsUnset() {
			vals[4] = psql.Arg(s.DeviceName.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.UserAgent.IsUnset() {
			vals[5] = psql.Arg(s.UserAgent.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if !s.IPAddress.IsUnset() {
			vals[6] = psql.Arg(s.IPAddress.MustGetNull())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[7] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.ExpiresAt.IsValue() {
			vals[8] = psql.Arg(s.ExpiresAt.MustGet())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if !s.RevokedAt.IsUnset() {
			vals[9] = psql.Arg(s.RevokedAt.MustGetNull())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s SessionSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s SessionSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 10)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.RefreshJti.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "refresh_jti")...),
			psql.Arg(s.RefreshJti),
		}})
	}

	if s.TokenVersion.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "token_version")...),
			psql.Arg(s.TokenVersion),
		}})
	}

	if !s.DeviceName.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "device_name")...),
			psql.Arg(s.DeviceName),
		}})
	}

	if !s.UserAgent.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_agent")...),
			psql.Arg(s.UserAgent),
		}})
	}

	if !s.IPAddress.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "ip_address")...),
			psql.Arg(s.IPAddress),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.ExpiresAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "expires_at")...),
			psql.Arg(s.ExpiresAt),
		}})
	}

	if !s.RevokedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "revoked_at")...),
			psql.Arg(s.RevokedAt),
		}})
	}

	return exprs
}

// FindSession retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindSession(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Session, error) {
	if len(cols) == 0 {
		return Sessions.Query(
			sm.Where(Sessions.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Sessions.Query(
		sm.Where(Sessions.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Sessions.Columns.Only(cols...)),
	).One(ctx, exec)
}

// SessionExists checks the presence of a single record by primary key
func SessionExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Sessions.Query(
		sm.Where(Sessions.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Session is retrieved from the database
func (o *Session) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Sessions.AfterSelectHooks.RunHooks(ctx, exec, SessionSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Sessions.AfterInsertHooks.RunHooks(ctx, exec, SessionSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Sessions.AfterUpdateHooks.RunHooks(ctx, exec, SessionSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Sessions.AfterDeleteHooks.RunHooks(ctx, exec, SessionSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Session
func (o *Session) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Session) pkEQ() dialect.Expression {
	return psql.Quote("sessions", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Session
func (o *Session) Update(ctx context.Context, exec bob.Executor, s *SessionSetter) error {
	v, err := Sessions.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Session record with an executor
func (o *Session) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Sessions.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Session using the executor
func (o *Session) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Sessions.Query(
		sm.Where(Sessions.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after SessionSlice is retrieved from the database
func (o SessionSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Sessions.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Sessions.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Sessions.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Sessions.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o SessionSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("sessions", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o SessionSlice) copyMatchingRows(from ...*Session) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o SessionSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Sessions.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Session:
				o.copyMatchingRows(retrieved)
			case []*Session:
				o.copyMatchingRows(retrieved...)
			case SessionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Session or a slice of Session
				// then run the AfterUpdateHooks on the slice
				_, err = Sessions.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o SessionSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Sessions.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Session:
				o.copyMatchingRows(retrieved)
			case []*Session:
				o.copyMatchingRows(retrieved...)
			case SessionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Session or a slice of Session
				// then run the AfterDeleteHooks on the slice
				_, err = Sessions.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o SessionSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals SessionSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Sessions.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o SessionSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Sessions.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o SessionSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Sessions.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on users
func (o *Session) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os SessionSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachSessionUser0(ctx context.Context, exec bob.Executor, count int, session0 *Session, user1 *User) (*Session, error) {
	setter := &SessionSetter{
		UserID: omit.From(user1.ID),
	}

	err := session0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachSessionUser0: %w", err)
	}

	return session0, nil
}

func (session0 *Session) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachSessionUser0(ctx, exec, 1, session0, user1)
	if err != nil {
		return err
	}

	session0.R.User = user1

	user1.R.Sessions = append(user1.R.Sessions, session0)

	return nil
}

func (session0 *Session) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachSessionUser0(ctx, exec, 1, session0, user1)
	if err != nil {
		return err
	}

	session0.R.User = user1

	user1.R.Sessions = append(user1.R.Sessions, session0)

	return nil
}

type sessionWhere[Q psql.Filterable] struct {
	ID           psql.WhereMod[Q, uuid.UUID]
	UserID       psql.WhereMod[Q, uuid.UUID]
	RefreshJti   psql.WhereMod[Q, uuid.UUID]
	TokenVersion psql.WhereMod[Q, int32]
	DeviceName   psql.WhereNullMod[Q, string]
	UserAgent    psql.WhereNullMod[Q, string]
	IPAddress    psql.WhereNullMod[Q, pgtypes.Inet]
	CreatedAt    psql.WhereMod[Q, time.Time]
	ExpiresAt    psql.WhereMod[Q, time.Time]
	RevokedAt    psql.WhereNullMod[Q, time.Time]
}

func (sessionWhere[Q]) AliasedAs(alias string) sessionWhere[Q] {
	return buildSessionWhere[Q](buildSessionColumns(alias))
}

func buildSessionWhere[Q psql.Filterable](cols sessionColumns) sessionWhere[Q] {
	return sessionWhere[Q]{
		ID:           psql.Where[Q, uuid.UUID](cols.ID),
		UserID:       psql.Where[Q, uuid.UUID](cols.UserID),
		RefreshJti:   psql.Where[Q, uuid.UUID](cols.RefreshJti),
		TokenVersion: psql.Where[Q, int32](cols.TokenVersion),
		DeviceName:   psql.WhereNull[Q, string](cols.DeviceName),
		UserAgent:    psql.WhereNull[Q, string](cols.UserAgent),
		IPAddress:    psql.WhereNull[Q, pgtypes.Inet](cols.IPAddress),
		CreatedAt:    psql.Where[Q, time.Time](cols.CreatedAt),
		ExpiresAt:    psql.Where[Q, time.Time](cols.ExpiresAt),
		RevokedAt:    psql.WhereNull[Q, time.Time](cols.RevokedAt),
	}
}

func (o *Session) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("session cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.Sessions = SessionSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("session has no relationship %q", name)
	}
}

type sessionPreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildSessionPreloader() sessionPreloader {
	return sessionPreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        Sessions,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type sessionThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildSessionThenLoader[Q orm.Loadable]() sessionThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return sessionThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the session's User into the .R struct
func (o *Session) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Sessions = SessionSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the session's User into the .R struct
func (os SessionSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.Sessions = append(rel.R.Sessions, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type sessionJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j sessionJoins[Q]) aliasedAs(alias string) sessionJoins[Q] {
	return buildSessionJoins[Q](buildSessionColumns(alias), j.typ)
}

func buildSessionJoins[Q dialect.Joinable](cols sessionColumns, typ string) sessionJoins[Q] {
	return sessionJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
