// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var PermissionErrors = &permissionErrors{
	ErrUniquePermissionsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "permissions",
		columns: []string{"id"},
		s:       "permissions_pkey",
	},

	ErrUniquePermissionsObjectActionKey: &UniqueConstraintError{
		schema:  "",
		table:   "permissions",
		columns: []string{"object", "action"},
		s:       "permissions_object_action_key",
	},
}

type permissionErrors struct {
	ErrUniquePermissionsPkey *UniqueConstraintError

	ErrUniquePermissionsObjectActionKey *UniqueConstraintError
}
