// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var RoleErrors = &roleErrors{
	ErrUniqueRolesPkey: &UniqueConstraintError{
		schema:  "",
		table:   "roles",
		columns: []string{"id"},
		s:       "roles_pkey",
	},

	ErrUniqueRolesNameKey: &UniqueConstraintError{
		schema:  "",
		table:   "roles",
		columns: []string{"name"},
		s:       "roles_name_key",
	},
}

type roleErrors struct {
	ErrUniqueRolesPkey *UniqueConstraintError

	ErrUniqueRolesNameKey *UniqueConstraintError
}
