// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var SessionErrors = &sessionErrors{
	ErrUniqueSessionsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "sessions",
		columns: []string{"id"},
		s:       "sessions_pkey",
	},

	ErrUniqueSessionsRefreshJtiKey: &UniqueConstraintError{
		schema:  "",
		table:   "sessions",
		columns: []string{"refresh_jti"},
		s:       "sessions_refresh_jti_key",
	},
}

type sessionErrors struct {
	ErrUniqueSessionsPkey *UniqueConstraintError

	ErrUniqueSessionsRefreshJtiKey *UniqueConstraintError
}
