// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const existsPermission = `-- name: ExistsPermission :one
SELECT EXISTS(
    SELECT 1 FROM permissions
    WHERE id = $1
)
`

func (q *Queries) ExistsPermission(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsPermission, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertPermission = `-- name: InsertPermission :exec
INSERT INTO permissions (object, action)
VALUES ($1, $2)
    ON CONFLICT (object, action) DO NOTHING
`

type InsertPermissionParams struct {
	Object string `db:"object" json:"object"`
	Action string `db:"action" json:"action"`
}

func (q *Queries) InsertPermission(ctx context.Context, arg InsertPermissionParams) error {
	_, err := q.db.Exec(ctx, insertPermission, arg.Object, arg.Action)
	return err
}
