// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const existsRole = `-- name: ExistsRole :one
SELECT EXISTS(
    SELECT 1 FROM roles
    WHERE id = $1
)
`

func (q *Queries) ExistsRole(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsRole, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertRole = `-- name: InsertRole :exec
INSERT INTO roles (name, description, is_system)
VALUES ($1, $2, $3)
    ON CONFLICT (name) DO NOTHING
`

type InsertRoleParams struct {
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
	IsSystem    *bool   `db:"is_system" json:"is_system"`
}

func (q *Queries) InsertRole(ctx context.Context, arg InsertRoleParams) error {
	_, err := q.db.Exec(ctx, insertRole, arg.Name, arg.Description, arg.IsSystem)
	return err
}
