// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/tencat-dev/go-api-base/internal/authz"
	"github.com/tencat-dev/go-api-base/internal/biz"
	"github.com/tencat-dev/go-api-base/internal/conf"
	"github.com/tencat-dev/go-api-base/internal/data"
	"github.com/tencat-dev/go-api-base/internal/infra/auth"
	"github.com/tencat-dev/go-api-base/internal/server"
	"github.com/tencat-dev/go-api-base/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(contextContext context.Context, bootstrap *conf.Bootstrap, logger log.Logger, helper *log.Helper) (*kratos.App, func(), error) {
	confServer := newServer(bootstrap)
	confAuthz := newAuthz(bootstrap)
	grpcServer := newGrpcServer(confServer)
	confData := newData(bootstrap)
	databaseConfig := newDatabaseConfig(confData)
	dataData, cleanup, err := data.NewData(contextContext, databaseConfig, helper)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, helper)
	iEnforcer, err := data.NewCasbinEnforcer(dataData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	casbinAuthz := data.NewCasbinAuthz(iEnforcer)
	manager := data.NewPermissionManager(casbinAuthz)
	hasher := auth.NewPasswordHasher()
	userBiz := biz.NewUserBiz(userRepo, manager, hasher)
	userServiceServer := service.NewUserService(userBiz)
	authRepo := data.NewAuthRepo(dataData, helper)
	checker := data.NewPermissionChecker(casbinAuthz)
	authBiz := biz.NewAuthBiz(authRepo, checker, hasher)
	confAuth := newAuth(bootstrap)
	jwt := newJwtConfig(confAuth)
	jwtMaker, err := auth.NewJWTMaker(jwt)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tokenMaker := auth.NewTokenMaker(jwtMaker)
	authServiceServer := service.NewAuthService(authBiz, tokenMaker)
	authzBiz := biz.NewAuthzBiz(manager, userRepo)
	authzServiceServer := service.NewAuthzService(authzBiz)
	authzRegistry := authz.NewAuthzRegistry()
	tokenParser := auth.TokenParser(jwtMaker)
	authzMiddleware := authz.NewAuthzMiddleware(checker, authzRegistry, userRepo, tokenParser)
	serverGrpcServer := server.NewGRPCServer(grpcServer, userServiceServer, authServiceServer, authzServiceServer, logger, authzMiddleware)
	httpServer := newHttpServer(confServer)
	serverHttpServer := server.NewHTTPServer(httpServer, userServiceServer, authServiceServer, authzServiceServer, logger, authzMiddleware)
	pprofServer := newPprofServer(confServer)
	serverPprofServer := server.NewPprofServer(pprofServer)
	roleRepo := data.NewRoleRepo(dataData, helper)
	roleBiz := biz.NewRoleBiz(roleRepo)
	permissionRepo := data.NewPermissionRepo(dataData, helper)
	permissionBiz := biz.NewPermissionBiz(permissionRepo)
	seederFromRegistry := authz.NewSeederFromRegistry(manager, authzRegistry, roleBiz, permissionBiz)
	app, cleanup2, err := newApp(contextContext, confServer, confAuthz, logger, serverGrpcServer, serverHttpServer, serverPprofServer, seederFromRegistry)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
